sbatch ./rnop.sbatch f 0
sbatch ./rnop.sbatch f 1
sbatch ./rnop.sbatch f 2
sbatch ./rnop.sbatch f 3
sbatch ./rnop.sbatch f 4
sbatch ./rnop.sbatch f 5
sbatch ./rnop.sbatch f 6
sbatch ./rnop.sbatch f 7
sbatch ./rnop.sbatch f 8
sbatch ./rnop.sbatch f 9
sbatch ./rnop.sbatch f 10
sbatch ./rnop.sbatch f 11
sbatch ./rnop.sbatch f 12
sbatch ./rnop.sbatch f 13
sbatch ./rnop.sbatch l 0
sbatch ./rnop.sbatch l 1
sbatch ./rnop.sbatch l 2
sbatch ./rnop.sbatch l 3
sbatch ./rnop.sbatch l 4
sbatch ./rnop.sbatch l 5
sbatch ./rnop.sbatch l 6
sbatch ./rnop.sbatch l 7
sbatch ./rnop.sbatch l 8
sbatch ./rnop.sbatch l 9
sbatch ./rnop.sbatch l 10
sbatch ./rnop.sbatch l 11
sbatch ./rnop.sbatch l 12
sbatch ./rnop.sbatch l 13
