sbatch ./sbatch/adnop/adnop_predict.sbatch 0 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 1 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 2 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 3 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 4 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 5 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 6 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 7 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 8 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 9 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 10 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 11 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 12 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 13 -e e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 0 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 1 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 2 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 3 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 4 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 5 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 6 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 7 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 8 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 9 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 10 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 11 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 12 -s e30
sbatch ./sbatch/adnop/adnop_predict.sbatch 13 -s e30
