sbatch ./sbatch/one_per/one_per.sbatch f 0
sbatch ./sbatch/one_per/one_per.sbatch f 1
sbatch ./sbatch/one_per/one_per.sbatch f 2
sbatch ./sbatch/one_per/one_per.sbatch f 3
sbatch ./sbatch/one_per/one_per.sbatch f 4
sbatch ./sbatch/one_per/one_per.sbatch f 5
sbatch ./sbatch/one_per/one_per.sbatch f 6
sbatch ./sbatch/one_per/one_per.sbatch f 7
sbatch ./sbatch/one_per/one_per.sbatch f 8
sbatch ./sbatch/one_per/one_per.sbatch f 9
sbatch ./sbatch/one_per/one_per.sbatch f 10
sbatch ./sbatch/one_per/one_per.sbatch f 11
sbatch ./sbatch/one_per/one_per.sbatch f 12
sbatch ./sbatch/one_per/one_per.sbatch f 13
sbatch ./sbatch/one_per/one_per.sbatch l 0
sbatch ./sbatch/one_per/one_per.sbatch l 1
sbatch ./sbatch/one_per/one_per.sbatch l 2
sbatch ./sbatch/one_per/one_per.sbatch l 3
sbatch ./sbatch/one_per/one_per.sbatch l 4
sbatch ./sbatch/one_per/one_per.sbatch l 5
sbatch ./sbatch/one_per/one_per.sbatch l 6
sbatch ./sbatch/one_per/one_per.sbatch l 7
sbatch ./sbatch/one_per/one_per.sbatch l 8
sbatch ./sbatch/one_per/one_per.sbatch l 9
sbatch ./sbatch/one_per/one_per.sbatch l 10
sbatch ./sbatch/one_per/one_per.sbatch l 11
sbatch ./sbatch/one_per/one_per.sbatch l 12
sbatch ./sbatch/one_per/one_per.sbatch l 13
